repos:
  - repo: https://github.com/psf/black.git
    rev: "24.10.0"
    hooks:
      - id: black

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-black
        name: nbqa-black
        description: Run 'black' on a Jupyter Notebook
        entry: nbqa black
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [black]

  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
        entry: isort
        args:
          - --profile=black 
          - --float-to-top

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-flake8
        args:
          - --ignore=E501,E712,W291,F632,E203,F821,F403,W391,F401
          - --exclude=.*,__init__.py
        name: nbqa-flake8
        description: Run 'flake8' on a Jupyter Notebook
        entry: nbqa flake8
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies:
          - flake8-variables-names
          - pep8-naming
          - flake8-functions-names
