"functions":
- "name": "config_lookup_string"
  "params":
  - "name": "config"
    "type": "bool "
  - "name": "path"
    "type": "bool "
  - "name": "value"
    "type": "bool "
  "return_type": "int"
  "signature": "int config_lookup_string(const config_t *, const char *, const char **)"
- "name": "config_read"
  "params":
  - "name": "config"
    "type": "bool "
  - "name": "stream"
    "type": "bool "
  "return_type": "int"
  "signature": "int config_read(config_t *, FILE *)"
- "name": "config_lookup_float"
  "params":
  - "name": "config"
    "type": "bool "
  - "name": "path"
    "type": "bool "
  - "name": "value"
    "type": "bool "
  "return_type": "int"
  "signature": "int config_lookup_float(const config_t *, const char *, double *)"
- "name": "config_lookup_bool"
  "params":
  - "name": "config"
    "type": "bool "
  - "name": "path"
    "type": "bool "
  - "name": "value"
    "type": "bool "
  "return_type": "int"
  "signature": "int config_lookup_bool(const config_t *, const char *, int *)"
- "name": "config_write_file"
  "params":
  - "name": "config"
    "type": "bool "
  - "name": "filename"
    "type": "bool "
  "return_type": "int"
  "signature": "int config_write_file(config_t *, const char *)"
- "name": "config_lookup"
  "params":
  - "name": "config"
    "type": "bool "
  - "name": "path"
    "type": "bool "
  "return_type": "void"
  "signature": "config_setting_t * config_lookup(const config_t *, const char *)"
- "name": "LLVMFuzzerCustomMutator"
  "params":
  - "name": "data"
    "type": "bool "
  - "name": "size"
    "type": "size_t"
  - "name": "max_size"
    "type": "size_t"
  - "name": "seed"
    "type": "int"
  "return_type": "size_t"
  "signature": "size_t LLVMFuzzerCustomMutator(uint8_t *, size_t, size_t, unsigned int)"
- "name": "config_lookup_int64"
  "params":
  - "name": "config"
    "type": "bool "
  - "name": "path"
    "type": "bool "
  - "name": "value"
    "type": "bool "
  "return_type": "int"
  "signature": "int config_lookup_int64(const config_t *, const char *, long long *)"
- "name": "config_lookup_int"
  "params":
  - "name": "config"
    "type": "bool "
  - "name": "path"
    "type": "bool "
  - "name": "value"
    "type": "bool "
  "return_type": "int"
  "signature": "int config_lookup_int(const config_t *, const char *, int *)"
- "name": "config_read_file"
  "params":
  - "name": "config"
    "type": "bool "
  - "name": "filename"
    "type": "bool "
  "return_type": "int"
  "signature": "int config_read_file(config_t *, const char *)"
"language": "c"
"project": "libconfig"
"target_name": "config_read_fuzzer"
"target_path": "/src/libconfig/fuzz/fuzz_config_read.c"
