steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - '-t'
  - us-central1-docker.pkg.dev/oss-fuzz-base/testing/oss-fuzz-gen-pull-request:pr-${_PR_NUMBER}
  - .
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - auth
    - configure-docker
    - us-central1-docker.pkg.dev
    - '--quiet'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - us-central1-docker.pkg.dev/oss-fuzz-base/testing/oss-fuzz-gen-pull-request:pr-${_PR_NUMBER}
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - '-t'
  - us-central1-docker.pkg.dev/oss-fuzz-base/oss-fuzz-gen/ci
  - --cache-from
  - us-central1-docker.pkg.dev/oss-fuzz-base/oss-fuzz-gen/ci
  - '-f'
  - ci/Dockerfile
  - .
- name: us-central1-docker.pkg.dev/oss-fuzz-base/oss-fuzz-gen/ci
  args: []
  env:
    - 'PULL_REQUEST_NUMBER=${_PR_NUMBER}'
    - 'BRANCH=${_HEAD_BRANCH}'
    - 'REPO=${_HEAD_REPO_URL}'
images:
- us-central1-docker.pkg.dev/oss-fuzz-base/oss-fuzz-gen/ci
logsBucket: gs://oss-fuzz-gen-ci-logs
