name: Build Docker image for PR

on:
  pull_request:

env:
  PR_ID: ${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag us-central1-docker.pkg.dev/oss-fuzz-base/testing/oss-fuzz-gen-pull-request:pr-${{ env.PR_ID }}
    - name: Authenticate to gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCLOUD_CREDENTIAL }}'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Auth to Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    - name: Push to Artifact Registry
      run: docker push us-central1-docker.pkg.dev/oss-fuzz-base/testing/oss-fuzz-gen-pull-request:pr-${{ env.PR_ID }}
